# Generated by Django 3.1.5 on 2021-01-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Sitede gösterilsin mi?'),
        ),
    ]
