# Generated by Django 3.1.5 on 2021-01-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210122_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slayt', 'verbose_name_plural': 'Slaytlar'},
        ),
    ]
