# Generated by Django 3.1.5 on 2021-01-22 19:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210122_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Resim')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma zamanı')),
                ('content', ckeditor.fields.RichTextField(max_length=200, verbose_name='İçerik')),
                ('slug', models.SlugField(editable=False)),
                ('active', models.BooleanField(default=False, verbose_name='Sitede gösterilsin mi?')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
            },
        ),
    ]
