# Generated by Django 3.1.5 on 2021-01-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='about',
            field=models.BooleanField(default=False, verbose_name='Neden Kiralama Başlığı için tıklayınız'),
        ),
    ]
