# Generated by Django 3.1.5 on 2021-01-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210122_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='adress',
            field=models.CharField(default='KaanFilo', max_length=75),
        ),
        migrations.AddField(
            model_name='blog',
            name='copyright_name',
            field=models.CharField(default='KaanFilo', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='KaanFilo', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='phone',
            field=models.CharField(default='KaanFilo', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='skype_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
