# Generated by Django 3.1.5 on 2021-01-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210123_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='İsim Soy:')),
                ('surname', models.CharField(max_length=30, verbose_name='Soyad:')),
                ('company', models.CharField(max_length=70, verbose_name='Firma:')),
                ('email', models.EmailField(max_length=254, verbose_name='Eposta adresi:')),
                ('number', models.SmallIntegerField(verbose_name='Telefon Numaranız:')),
                ('city', models.CharField(max_length=30, verbose_name='Şehir')),
                ('number_of_car', models.SmallIntegerField(verbose_name='Kiralanacak Araç Sayısı:')),
                ('renting_time', models.SmallIntegerField(verbose_name='Kiralanacak Gün Sayısı:')),
                ('message', models.TextField(verbose_name='Mesajınız:')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
            },
        ),
    ]
