# Generated by Django 3.1.5 on 2021-01-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210124_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Ayar', 'verbose_name_plural': 'Ayarlar'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='teams',
            field=models.BooleanField(default=False, verbose_name='KaanFilo ekibinin sergilenmesi için tıklayınız.'),
        ),
    ]
