# Generated by Django 3.1.5 on 2021-01-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210124_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='about',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='content',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='features',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='get_startted',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='header',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='testimonials',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='youtube_url',
        ),
    ]
