# Generated by Django 3.1.5 on 2021-01-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210124_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub_content',
            field=models.CharField(default=1, max_length=100, verbose_name='Kısa İçerik'),
            preserve_default=False,
        ),
    ]
