# Generated by Django 3.1.5 on 2021-01-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='phone2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
