# Generated by Django 3.1.5 on 2021-01-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210124_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='content',
            field=models.TextField(max_length=350, verbose_name='Hakkımızda kısmı için içerik:'),
        ),
    ]
