# Generated by Django 3.1.5 on 2021-01-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210124_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='font',
            field=models.CharField(choices=[('icofont-auto-mobile', 'araba'), ('icofont-automation', 'hizmetler'), ('icofont-bullseye', 'avantaj'), ('ri-store-line', 'dükkan')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='font_title',
            field=models.CharField(default=1, max_length=50, verbose_name='Font Başlık'),
            preserve_default=False,
        ),
    ]
