# Generated by Django 3.1.5 on 2021-01-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210124_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='whatsapp_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
