# Generated by Django 3.1.5 on 2021-02-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_setting_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='Kaanfilo', max_length=150, verbose_name="Google'da çıkacak olan yazı"),
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(default='Kaan Filo, araç kiralama', max_length=150, verbose_name="Google'da aramalarda çıkabilmek için gerekli anahtar kelimler"),
        ),
    ]
