# Generated by Django 3.1.4 on 2021-03-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210203_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='googleMap',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Googlemap iframe'),
        ),
    ]
